Gem::Specification.new do |s|
  s.name              = %q{refinerycms-reference-link}
  s.version           = %q{0.0.1}
  s.description       = %q{Wiki like links integration into RefineryCMS.}
  s.date              = %q{2011-05-27}
  s.summary           = %q{Ruby on Rails wiki like links for RefineryCMS.}
  s.email             = %q{retro@ballgag.cz}
  s.homepage          = %q{https://github.com/SmartMedia/refinerycms-reference-link}
  s.authors           = ['Smart Media Agency']
  s.require_paths     = %w(lib)

  s.files             = %w(
    config.ru
    app
    app/controllers
    app/controllers/application_controller.rb
    app/views
    app/views/shared
    app/views/shared/_google_analytics.html.erb
    app/views/shared/_ie6check.html.erb
    app/views/shared/_menu.html.erb
    app/views/shared/_message.html.erb
    app/views/shared/_header.html.erb
    app/views/shared/_javascripts.html.erb
    app/views/shared/_footer.html.erb
    app/views/shared/_draft_page_message.html.erb
    app/views/shared/_no_script.html.erb
    app/views/shared/_site_bar.html.erb
    app/views/shared/_head.html.erb
    app/views/shared/_slide_header.html.erb
    app/views/shared/_html_tag.html.erb
    app/views/shared/_menu_branch.html.erb
    app/views/pages
    app/views/pages/home.html.erb
    app/views/pages/_side.html.erb
    app/views/pages/show.html.erb
    app/views/layouts
    app/views/layouts/application.html.erb
    app/views/sitemap
    app/views/sitemap/index.xml.builder
    app/helpers
    app/helpers/application_helper.rb
    lib
    lib/tasks
    lib/tasks/migrate_friendly_id_models_to_slug_url.rake
    lib/tasks/migrate_url_slug_from_title_in_service.rake
    public
    public/images
    public/images/bg_ft.png
    public/images/bg_hd_oranger.png
    public/images/logo.png
    public/images/sledujte_nas.png
    public/images/imac_arrow.png
    public/images/junk_reference2.png
    public/images/bg_reference.png
    public/images/buttons_pnl.png
    public/images/buttons.png
    public/images/mn_overlay.png
    public/images/junk_google2.png
    public/images/icons_social.png
    public/images/bg_ft_opacity.png
    public/images/uglyboy.png
    public/images/lightbox
    public/images/lightbox/lightbox-btn-next.gif
    public/images/lightbox/lightbox-blank.gif
    public/images/lightbox/lightbox-btn-prev.gif
    public/images/lightbox/lightbox-btn-close.gif
    public/images/lightbox/lightbox-ico-loading.gif
    public/images/bg_search.png
    public/images/bg_certificate_buttons.png
    public/images/mn_separator.png
    public/images/box_corners.png
    public/images/junk_reference1.png
    public/images/junk_google3.png
    public/images/junk_foto1.png
    public/images/icons.png
    public/images/junk_google1.png
    public/images/junk_etarget.png
    public/images/bg_box.png
    public/images/bookmark.png
    public/images/bg_inset.png
    public/images/imac.png
    public/images/rails.png
    public/images/bg_hd_shaders.png
    public/images/junk_image1.png
    public/images/contact_sokolovska.png
    public/images/mn_gradient.png
    public/images/bg_certificate.png
    public/robots.txt
    public/stylesheets
    public/stylesheets/home.css
    public/stylesheets/jquery.lightbox-0.5.css
    public/stylesheets/formatting.css
    public/stylesheets/theme.css
    public/stylesheets/application.css
    public/stylesheets/seo.css
    public/500.html
    public/index.html.backup
    public/404.html
    public/422.html
    public/favicon.ico
    public/javascripts
    public/javascripts/translations.js
    public/javascripts/jquery-min.js
    public/javascripts/admin.js
    public/javascripts/application.js
    public/javascripts/jquery-ui-custom-min.js
    public/javascripts/jquery.js
    public/javascripts/jquery.lightbox-0.5.js
    public/javascripts/refinerycms.js
    public/javascripts/seo-init-service.js
    public/javascripts/seo.js
    README
    vendor
    vendor/plugins
    vendor/design
    vendor/design/bg_ft.png
    vendor/design/_slovnik_pojmu.html
    vendor/design/bg_hd_oranger.png
    vendor/design/logo.png
    vendor/design/sledujte_nas.png
    vendor/design/imac_arrow.png
    vendor/design/junk_image2.png
    vendor/design/_homepage.html
    vendor/design/junk_reference2.png
    vendor/design/_clanek_a_sidemenu.html
    vendor/design/ellipsis.xml
    vendor/design/bg_reference.png
    vendor/design/_clanek_profilspolecnosti.html
    vendor/design/buttons_pnl.png
    vendor/design/buttons.png
    vendor/design/_contact.html
    vendor/design/mn_overlay.png
    vendor/design/junk_google2.png
    vendor/design/icons_social.png
    vendor/design/bg_ft_opacity.png
    vendor/design/uglyboy.png
    vendor/design/application.js
    vendor/design/bg_search.png
    vendor/design/_kariera.html
    vendor/design/bg_certificate_buttons.png
    vendor/design/mn_separator.png
    vendor/design/box_corners.png
    vendor/design/_nas_tym.html
    vendor/design/junk_reference1.png
    vendor/design/junk_google3.png
    vendor/design/icons.psd
    vendor/design/junk_foto1.png
    vendor/design/icons.png
    vendor/design/junk_google1.png
    vendor/design/junk_etarget.png
    vendor/design/buttons.psd
    vendor/design/bg_box.png
    vendor/design/icons_social.psd
    vendor/design/favicon.ico
    vendor/design/bookmark.png
    vendor/design/bg_inset.png
    vendor/design/imac.png
    vendor/design/bg_hd_shaders.png
    vendor/design/junk_image1.png
    vendor/design/buttons_pnl.psd
    vendor/design/mn_gradient.png
    vendor/design/application.css
    vendor/design/bg_certificate.png
    vendor/design-admin
    vendor/design-admin/bg_separator.png
    vendor/design-admin/bg_status.png
    vendor/design-admin/layout.html
    vendor/design-admin/application.js
    vendor/design-admin/down_arrow.png
    vendor/design-admin/application.css
    vendor/engines
    vendor/engines/services
    vendor/engines/services/features
    vendor/engines/services/features/step_definitions
    vendor/engines/services/features/step_definitions/service_steps.rb
    vendor/engines/services/features/support
    vendor/engines/services/features/support/paths.rb
    vendor/engines/services/features/manage_services.feature
    vendor/engines/services/features/visit_services.feature
    vendor/engines/services/app
    vendor/engines/services/app/controllers
    vendor/engines/services/app/controllers/services_controller.rb
    vendor/engines/services/app/controllers/admin
    vendor/engines/services/app/controllers/admin/services_dialogs_controller.rb
    vendor/engines/services/app/controllers/admin/services_controller.rb
    vendor/engines/services/app/controllers/admin/service_parts_controller.rb
    vendor/engines/services/app/views
    vendor/engines/services/app/views/services
    vendor/engines/services/app/views/services/_side.html.erb
    vendor/engines/services/app/views/services/index.html.erb
    vendor/engines/services/app/views/services/show.html.erb
    vendor/engines/services/app/views/admin
    vendor/engines/services/app/views/admin/services_dialogs
    vendor/engines/services/app/views/admin/services_dialogs/_service_link.html.erb
    vendor/engines/services/app/views/admin/services_dialogs/link_to.html.erb
    vendor/engines/services/app/views/admin/services
    vendor/engines/services/app/views/admin/services/_form_advanced_options.html.erb
    vendor/engines/services/app/views/admin/services/_records.html.erb
    vendor/engines/services/app/views/admin/services/new.html.erb
    vendor/engines/services/app/views/admin/services/_locale_picker.html.erb
    vendor/engines/services/app/views/admin/services/_form_fields_after_title.html.erb
    vendor/engines/services/app/views/admin/services/index.html.erb
    vendor/engines/services/app/views/admin/services/_service_part_field.html.erb
    vendor/engines/services/app/views/admin/services/_form_new_service_parts.html.erb
    vendor/engines/services/app/views/admin/services/_actions.html.erb
    vendor/engines/services/app/views/admin/services/_form_advanced_options_seo.html.erb
    vendor/engines/services/app/views/admin/services/_form.html.erb
    vendor/engines/services/app/views/admin/services/edit.html.erb
    vendor/engines/services/app/views/admin/services/_form_service_parts.html.erb
    vendor/engines/services/app/views/admin/services/_service.html.erb
    vendor/engines/services/app/views/admin/services/_sortable_list.html.erb
    vendor/engines/services/app/models
    vendor/engines/services/app/models/service_part.rb
    vendor/engines/services/app/models/service.rb
    vendor/engines/services/app/helpers
    vendor/engines/services/app/helpers/services_helper.rb
    vendor/engines/services/app/presenters
    vendor/engines/services/app/presenters/service_presenter.rb
    vendor/engines/services/spec
    vendor/engines/services/spec/models
    vendor/engines/services/spec/models/service_spec.rb
    vendor/engines/services/lib
    vendor/engines/services/lib/gemspec.rb
    vendor/engines/services/lib/services
    vendor/engines/services/lib/services/tabs.rb
    vendor/engines/services/lib/services/marketable_routes.rb
    vendor/engines/services/lib/generators
    vendor/engines/services/lib/generators/refinerycms_services_generator.rb
    vendor/engines/services/lib/refinerycms-services.rb
    vendor/engines/services/lib/refinery
    vendor/engines/services/lib/refinery/services
    vendor/engines/services/lib/refinery/services/instance_methods.rb
    vendor/engines/services/lib/refinery/services/admin
    vendor/engines/services/lib/refinery/services/admin/instance_methods.rb
    vendor/engines/services/config
    vendor/engines/services/config/routes.rb
    vendor/engines/services/config/locales
    vendor/engines/services/config/locales/pl.yml
    vendor/engines/services/config/locales/de.yml
    vendor/engines/services/config/locales/nb.yml
    vendor/engines/services/config/locales/sk.yml
    vendor/engines/services/config/locales/sv.yml
    vendor/engines/services/config/locales/lt.yml
    vendor/engines/services/config/locales/sl.yml
    vendor/engines/services/config/locales/el.yml
    vendor/engines/services/config/locales/ru.yml
    vendor/engines/services/config/locales/it.yml
    vendor/engines/services/config/locales/lolcat.yml
    vendor/engines/services/config/locales/fi.yml
    vendor/engines/services/config/locales/nl.yml
    vendor/engines/services/config/locales/cs.yml
    vendor/engines/services/config/locales/en.yml
    vendor/engines/services/config/locales/da.yml
    vendor/engines/services/config/locales/jp.yml
    vendor/engines/services/config/locales/pt-BR.yml
    vendor/engines/services/config/locales/es.yml
    vendor/engines/services/config/locales/zh-TW.yml
    vendor/engines/services/config/locales/fr.yml
    vendor/engines/services/config/locales/lv.yml
    vendor/engines/services/config/locales/zh-CN.yml
    vendor/engines/services/config/locales/rs.yml
    vendor/engines/services/config/locales/vi.yml
    vendor/engines/services/license.md
    vendor/engines/services/db
    vendor/engines/services/db/migrate
    vendor/engines/services/db/migrate/20110307025652_translate_custom_title_on_services.rb
    vendor/engines/services/db/migrate/20100913234708_create_refinerycms_services_schema.rb
    vendor/engines/services/db/migrate/20101216194133_remove_cached_slug_from_services.rb
    vendor/engines/services/db/migrate/20110329080451_create_seo_meta.rb
    vendor/engines/services/db/migrate/20101214040815_translate_service_plugin.rb
    vendor/engines/services/db/migrate/20110314213540_remove_translated_fields_from_services.rb
    vendor/engines/services/db/seeds
    vendor/engines/services/db/seeds/services.rb
    vendor/engines/references
    vendor/engines/references/features
    vendor/engines/references/features/manage_references.feature
    vendor/engines/references/features/step_definitions
    vendor/engines/references/features/step_definitions/reference_steps.rb
    vendor/engines/references/features/support
    vendor/engines/references/features/support/paths.rb
    vendor/engines/references/app
    vendor/engines/references/app/controllers
    vendor/engines/references/app/controllers/references_controller.rb
    vendor/engines/references/app/controllers/admin
    vendor/engines/references/app/controllers/admin/references_controller.rb
    vendor/engines/references/app/views
    vendor/engines/references/app/views/references
    vendor/engines/references/app/views/references/index.html.erb
    vendor/engines/references/app/views/references/show.html.erb
    vendor/engines/references/app/views/admin
    vendor/engines/references/app/views/admin/references
    vendor/engines/references/app/views/admin/references/_records.html.erb
    vendor/engines/references/app/views/admin/references/_reference.html.erb
    vendor/engines/references/app/views/admin/references/new.html.erb
    vendor/engines/references/app/views/admin/references/_references.html.erb
    vendor/engines/references/app/views/admin/references/index.html.erb
    vendor/engines/references/app/views/admin/references/_actions.html.erb
    vendor/engines/references/app/views/admin/references/_form.html.erb
    vendor/engines/references/app/views/admin/references/edit.html.erb
    vendor/engines/references/app/views/admin/references/_sortable_list.html.erb
    vendor/engines/references/app/models
    vendor/engines/references/app/models/reference.rb
    vendor/engines/references/readme.md
    vendor/engines/references/spec
    vendor/engines/references/spec/models
    vendor/engines/references/spec/models/reference_spec.rb
    vendor/engines/references/lib
    vendor/engines/references/lib/generators
    vendor/engines/references/lib/generators/refinerycms_references_generator.rb
    vendor/engines/references/lib/refinerycms-references.rb
    vendor/engines/references/lib/tasks
    vendor/engines/references/lib/tasks/references.rake
    vendor/engines/references/config
    vendor/engines/references/config/routes.rb
    vendor/engines/references/config/locales
    vendor/engines/references/config/locales/nb.yml
    vendor/engines/references/config/locales/lolcat.yml
    vendor/engines/references/config/locales/nl.yml
    vendor/engines/references/config/locales/en.yml
    vendor/engines/references/db
    vendor/engines/references/db/migrate
    vendor/engines/references/db/migrate/create_references.rb
    vendor/engines/references/db/seeds
    vendor/engines/references/db/seeds/references.rb
    vendor/engines/offices
    vendor/engines/offices/features
    vendor/engines/offices/features/step_definitions
    vendor/engines/offices/features/step_definitions/office_steps.rb
    vendor/engines/offices/features/support
    vendor/engines/offices/features/support/paths.rb
    vendor/engines/offices/features/manage_offices.feature
    vendor/engines/offices/app
    vendor/engines/offices/app/mailers
    vendor/engines/offices/app/mailers/contact_mailer.rb
    vendor/engines/offices/app/controllers
    vendor/engines/offices/app/controllers/admin
    vendor/engines/offices/app/controllers/admin/offices_controller.rb
    vendor/engines/offices/app/controllers/offices_controller.rb
    vendor/engines/offices/app/views
    vendor/engines/offices/app/views/contact_mailer
    vendor/engines/offices/app/views/contact_mailer/form_email.text.erb
    vendor/engines/offices/app/views/offices
    vendor/engines/offices/app/views/offices/index.html.erb
    vendor/engines/offices/app/views/offices/show.html.erb
    vendor/engines/offices/app/views/admin
    vendor/engines/offices/app/views/admin/offices
    vendor/engines/offices/app/views/admin/offices/_office.html.erb
    vendor/engines/offices/app/views/admin/offices/_records.html.erb
    vendor/engines/offices/app/views/admin/offices/new.html.erb
    vendor/engines/offices/app/views/admin/offices/_offices.html.erb
    vendor/engines/offices/app/views/admin/offices/index.html.erb
    vendor/engines/offices/app/views/admin/offices/_actions.html.erb
    vendor/engines/offices/app/views/admin/offices/_form.html.erb
    vendor/engines/offices/app/views/admin/offices/edit.html.erb
    vendor/engines/offices/app/views/admin/offices/_sortable_list.html.erb
    vendor/engines/offices/app/models
    vendor/engines/offices/app/models/office.rb
    vendor/engines/offices/readme.md
    vendor/engines/offices/spec
    vendor/engines/offices/spec/models
    vendor/engines/offices/spec/models/office_spec.rb
    vendor/engines/offices/lib
    vendor/engines/offices/lib/generators
    vendor/engines/offices/lib/generators/refinerycms_offices_generator.rb
    vendor/engines/offices/lib/refinerycms-offices.rb
    vendor/engines/offices/lib/tasks
    vendor/engines/offices/lib/tasks/offices.rake
    vendor/engines/offices/config
    vendor/engines/offices/config/routes.rb
    vendor/engines/offices/config/locales
    vendor/engines/offices/config/locales/nb.yml
    vendor/engines/offices/config/locales/lolcat.yml
    vendor/engines/offices/config/locales/nl.yml
    vendor/engines/offices/config/locales/en.yml
    vendor/engines/offices/db
    vendor/engines/offices/db/migrate
    vendor/engines/offices/db/migrate/create_offices.rb
    vendor/engines/offices/db/seeds
    vendor/engines/offices/db/seeds/offices.rb
    vendor/engines/jobs
    vendor/engines/jobs/features
    vendor/engines/jobs/features/manage_jobs.feature
    vendor/engines/jobs/features/step_definitions
    vendor/engines/jobs/features/step_definitions/job_steps.rb
    vendor/engines/jobs/features/support
    vendor/engines/jobs/features/support/paths.rb
    vendor/engines/jobs/app
    vendor/engines/jobs/app/controllers
    vendor/engines/jobs/app/controllers/jobs_controller.rb
    vendor/engines/jobs/app/controllers/admin
    vendor/engines/jobs/app/controllers/admin/jobs_controller.rb
    vendor/engines/jobs/app/views
    vendor/engines/jobs/app/views/jobs
    vendor/engines/jobs/app/views/jobs/index.html.erb
    vendor/engines/jobs/app/views/jobs/show.html.erb
    vendor/engines/jobs/app/views/admin
    vendor/engines/jobs/app/views/admin/jobs
    vendor/engines/jobs/app/views/admin/jobs/_records.html.erb
    vendor/engines/jobs/app/views/admin/jobs/new.html.erb
    vendor/engines/jobs/app/views/admin/jobs/_job.html.erb
    vendor/engines/jobs/app/views/admin/jobs/index.html.erb
    vendor/engines/jobs/app/views/admin/jobs/_jobs.html.erb
    vendor/engines/jobs/app/views/admin/jobs/_actions.html.erb
    vendor/engines/jobs/app/views/admin/jobs/_form.html.erb
    vendor/engines/jobs/app/views/admin/jobs/edit.html.erb
    vendor/engines/jobs/app/views/admin/jobs/_sortable_list.html.erb
    vendor/engines/jobs/app/models
    vendor/engines/jobs/app/models/job.rb
    vendor/engines/jobs/readme.md
    vendor/engines/jobs/spec
    vendor/engines/jobs/spec/models
    vendor/engines/jobs/spec/models/job_spec.rb
    vendor/engines/jobs/lib
    vendor/engines/jobs/lib/generators
    vendor/engines/jobs/lib/generators/refinerycms_jobs_generator.rb
    vendor/engines/jobs/lib/tasks
    vendor/engines/jobs/lib/tasks/jobs.rake
    vendor/engines/jobs/lib/refinerycms-jobs.rb
    vendor/engines/jobs/config
    vendor/engines/jobs/config/routes.rb
    vendor/engines/jobs/config/locales
    vendor/engines/jobs/config/locales/nb.yml
    vendor/engines/jobs/config/locales/lolcat.yml
    vendor/engines/jobs/config/locales/nl.yml
    vendor/engines/jobs/config/locales/en.yml
    vendor/engines/jobs/db
    vendor/engines/jobs/db/migrate
    vendor/engines/jobs/db/migrate/create_jobs.rb
    vendor/engines/jobs/db/seeds
    vendor/engines/jobs/db/seeds/jobs.rb
    vendor/engines/downloads
    vendor/engines/downloads/features
    vendor/engines/downloads/features/step_definitions
    vendor/engines/downloads/features/step_definitions/download_steps.rb
    vendor/engines/downloads/features/support
    vendor/engines/downloads/features/support/paths.rb
    vendor/engines/downloads/features/manage_downloads.feature
    vendor/engines/downloads/app
    vendor/engines/downloads/app/controllers
    vendor/engines/downloads/app/controllers/downloads_controller.rb
    vendor/engines/downloads/app/controllers/admin
    vendor/engines/downloads/app/controllers/admin/downloads_controller.rb
    vendor/engines/downloads/app/views
    vendor/engines/downloads/app/views/downloads
    vendor/engines/downloads/app/views/downloads/_side.html.erb
    vendor/engines/downloads/app/views/downloads/index.html.erb
    vendor/engines/downloads/app/views/downloads/show.html.erb
    vendor/engines/downloads/app/views/admin
    vendor/engines/downloads/app/views/admin/downloads
    vendor/engines/downloads/app/views/admin/downloads/_records.html.erb
    vendor/engines/downloads/app/views/admin/downloads/new.html.erb
    vendor/engines/downloads/app/views/admin/downloads/_downloads.html.erb
    vendor/engines/downloads/app/views/admin/downloads/index.html.erb
    vendor/engines/downloads/app/views/admin/downloads/_download.html.erb
    vendor/engines/downloads/app/views/admin/downloads/_actions.html.erb
    vendor/engines/downloads/app/views/admin/downloads/_form.html.erb
    vendor/engines/downloads/app/views/admin/downloads/edit.html.erb
    vendor/engines/downloads/app/views/admin/downloads/_sortable_list.html.erb
    vendor/engines/downloads/app/models
    vendor/engines/downloads/app/models/download.rb
    vendor/engines/downloads/app/models/download_category.rb
    vendor/engines/downloads/readme.md
    vendor/engines/downloads/spec
    vendor/engines/downloads/spec/models
    vendor/engines/downloads/spec/models/download_spec.rb
    vendor/engines/downloads/lib
    vendor/engines/downloads/lib/refinerycms-downloads.rb
    vendor/engines/downloads/lib/generators
    vendor/engines/downloads/lib/generators/refinerycms_downloads_generator.rb
    vendor/engines/downloads/lib/tasks
    vendor/engines/downloads/lib/tasks/downloads.rake
    vendor/engines/downloads/config
    vendor/engines/downloads/config/routes.rb
    vendor/engines/downloads/config/locales
    vendor/engines/downloads/config/locales/nb.yml
    vendor/engines/downloads/config/locales/lolcat.yml
    vendor/engines/downloads/config/locales/nl.yml
    vendor/engines/downloads/config/locales/en.yml
    vendor/engines/downloads/db
    vendor/engines/downloads/db/migrate
    vendor/engines/downloads/db/migrate/create_download_categories.rb
    vendor/engines/downloads/db/migrate/create_downloads.rb
    vendor/engines/downloads/db/seeds
    vendor/engines/downloads/db/seeds/downloads.rb
    vendor/engines/downloads/db/seeds/download_categories.rb
    vendor/engines/employees
    vendor/engines/employees/features
    vendor/engines/employees/features/step_definitions
    vendor/engines/employees/features/step_definitions/employee_steps.rb
    vendor/engines/employees/features/support
    vendor/engines/employees/features/support/paths.rb
    vendor/engines/employees/features/manage_employees.feature
    vendor/engines/employees/app
    vendor/engines/employees/app/controllers
    vendor/engines/employees/app/controllers/employees_controller.rb
    vendor/engines/employees/app/controllers/admin
    vendor/engines/employees/app/controllers/admin/employees_controller.rb
    vendor/engines/employees/app/views
    vendor/engines/employees/app/views/employees
    vendor/engines/employees/app/views/employees/index.html.erb
    vendor/engines/employees/app/views/employees/show.html.erb
    vendor/engines/employees/app/views/admin
    vendor/engines/employees/app/views/admin/employees
    vendor/engines/employees/app/views/admin/employees/_records.html.erb
    vendor/engines/employees/app/views/admin/employees/_employees.html.erb
    vendor/engines/employees/app/views/admin/employees/_employee.html.erb
    vendor/engines/employees/app/views/admin/employees/new.html.erb
    vendor/engines/employees/app/views/admin/employees/index.html.erb
    vendor/engines/employees/app/views/admin/employees/_actions.html.erb
    vendor/engines/employees/app/views/admin/employees/_form.html.erb
    vendor/engines/employees/app/views/admin/employees/edit.html.erb
    vendor/engines/employees/app/views/admin/employees/_sortable_list.html.erb
    vendor/engines/employees/app/models
    vendor/engines/employees/app/models/employee.rb
    vendor/engines/employees/readme.md
    vendor/engines/employees/spec
    vendor/engines/employees/spec/models
    vendor/engines/employees/spec/models/employee_spec.rb
    vendor/engines/employees/lib
    vendor/engines/employees/lib/generators
    vendor/engines/employees/lib/generators/refinerycms_employees_generator.rb
    vendor/engines/employees/lib/refinerycms-employees.rb
    vendor/engines/employees/lib/tasks
    vendor/engines/employees/lib/tasks/employees.rake
    vendor/engines/employees/config
    vendor/engines/employees/config/routes.rb
    vendor/engines/employees/config/locales
    vendor/engines/employees/config/locales/nb.yml
    vendor/engines/employees/config/locales/lolcat.yml
    vendor/engines/employees/config/locales/nl.yml
    vendor/engines/employees/config/locales/en.yml
    vendor/engines/employees/db
    vendor/engines/employees/db/migrate
    vendor/engines/employees/db/migrate/create_employees.rb
    vendor/engines/employees/db/seeds
    vendor/engines/employees/db/seeds/employees.rb
    vendor/engines/dictionary_items
    vendor/engines/dictionary_items/features
    vendor/engines/dictionary_items/features/step_definitions
    vendor/engines/dictionary_items/features/step_definitions/dictionary_item_steps.rb
    vendor/engines/dictionary_items/features/support
    vendor/engines/dictionary_items/features/support/paths.rb
    vendor/engines/dictionary_items/features/manage_dictionary_items.feature
    vendor/engines/dictionary_items/app
    vendor/engines/dictionary_items/app/mailers
    vendor/engines/dictionary_items/app/mailers/dictionary_mailer.rb
    vendor/engines/dictionary_items/app/controllers
    vendor/engines/dictionary_items/app/controllers/dictionary_items_controller.rb
    vendor/engines/dictionary_items/app/controllers/admin
    vendor/engines/dictionary_items/app/controllers/admin/dictionary_items_controller.rb
    vendor/engines/dictionary_items/app/views
    vendor/engines/dictionary_items/app/views/dictionary_mailer
    vendor/engines/dictionary_items/app/views/dictionary_mailer/form_email.text.erb
    vendor/engines/dictionary_items/app/views/dictionary_items
    vendor/engines/dictionary_items/app/views/dictionary_items/_contact_form.html.erb
    vendor/engines/dictionary_items/app/views/dictionary_items/index.html.erb
    vendor/engines/dictionary_items/app/views/dictionary_items/show.html.erb
    vendor/engines/dictionary_items/app/views/admin
    vendor/engines/dictionary_items/app/views/admin/dictionary_items
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/_records.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/new.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/_dictionary_items.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/_dictionary_item.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/index.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/_actions.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/_form.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/edit.html.erb
    vendor/engines/dictionary_items/app/views/admin/dictionary_items/_sortable_list.html.erb
    vendor/engines/dictionary_items/app/models
    vendor/engines/dictionary_items/app/models/dictionary_item.rb
    vendor/engines/dictionary_items/readme.md
    vendor/engines/dictionary_items/spec
    vendor/engines/dictionary_items/spec/models
    vendor/engines/dictionary_items/spec/models/dictionary_item_spec.rb
    vendor/engines/dictionary_items/lib
    vendor/engines/dictionary_items/lib/generators
    vendor/engines/dictionary_items/lib/generators/refinerycms_dictionary_items_generator.rb
    vendor/engines/dictionary_items/lib/tasks
    vendor/engines/dictionary_items/lib/tasks/dictionary_items.rake
    vendor/engines/dictionary_items/lib/refinerycms-dictionary_items.rb
    vendor/engines/dictionary_items/config
    vendor/engines/dictionary_items/config/routes.rb
    vendor/engines/dictionary_items/config/locales
    vendor/engines/dictionary_items/config/locales/nb.yml
    vendor/engines/dictionary_items/config/locales/lolcat.yml
    vendor/engines/dictionary_items/config/locales/nl.yml
    vendor/engines/dictionary_items/config/locales/en.yml
    vendor/engines/dictionary_items/db
    vendor/engines/dictionary_items/db/migrate
    vendor/engines/dictionary_items/db/migrate/create_dictionary_items.rb
    vendor/engines/dictionary_items/db/seeds
    vendor/engines/dictionary_items/db/seeds/dictionary_items.rb
    vendor/engines/refinerycms-reference-link
    vendor/engines/refinerycms-reference-link/readme.md
    vendor/engines/refinerycms-reference-link/spec
    vendor/engines/refinerycms-reference-link/lib
    vendor/engines/refinerycms-reference-link/lib/gemspec.rb
    vendor/engines/refinerycms-reference-link/lib/refinery
    vendor/engines/refinerycms-reference-link/lib/refinery/reference_link
    vendor/engines/refinerycms-reference-link/lib/refinery/reference_link/version.rb
    vendor/engines/smart_admin
    vendor/engines/smart_admin/config
    vendor/engines/smart_admin/config/locales
    config
    config/database.yml.sqlite3
    config/database.yml
    config/database.yml.mysql
    config/database.yml.postgresql
    config/environment.rb
    config/application.rb
    config/environments
    config/environments/production.rb
    config/environments/test.rb
    config/environments/development.rb
    config/routes.rb
    config/setup_load_paths.rb
    config/boot.rb
    config/locales
    config/locales/en.yml
    config/i18n-js.yml
    config/initializers
    config/initializers/devise.rb
    config/initializers/footnotes.rb
    config/initializers/inflections.rb
    config/initializers/backtrace_silencers.rb
    config/initializers/mime_types.rb
    config/initializers/secret_token.rb
    config/initializers/session_store.rb
    Gemfile.lock
    Gemfile.backup
    Rakefile
    autotest
    autotest/discover.rb
    autotest/autotest.rb
    db
    db/schema.rb
    db/migrate
    db/migrate/20110411125555_create_seo_meta.rb
    db/migrate/20110411125544_create_refinerycms_authentication_schema.rb
    db/migrate/20110411125545_add_missing_indexes_to_roles_users.rb
    db/migrate/20110509152345_create_offices.rb
    db/migrate/20110505151059_create_refinerycms_services_schema.rb
    db/migrate/20110516112958_create_dictionary_items.rb
    db/migrate/20110526143718_add_slug_url_to_friendly_id_models.rb
    db/migrate/20110411125547_add_remember_created_at_to_users.rb
    db/migrate/20110422150344_create_employees.rb
    db/migrate/20110411125556_create_refinerycms_resources_schema.rb
    db/migrate/20110411125550_create_refinerycms_pages_schema.rb
    db/migrate/20110505151060_translate_service_plugin.rb
    db/migrate/20110505151063_remove_translated_fields_from_services.rb
    db/migrate/20110505151062_translate_custom_title_on_services.rb
    db/migrate/20110526161425_migrate_dictionary_items_to_globalize.rb
    db/migrate/20110428130145_create_references.rb
    db/migrate/20110411125546_change_to_devise_users_table.rb
    db/migrate/20110411125552_remove_cached_slug_from_pages.rb
    db/migrate/20110411125542_create_refinerycms_settings_schema.rb
    db/migrate/20110517115626_create_downloads.rb
    db/migrate/20110426145306_create_jobs.rb
    db/migrate/20110526161833_add_slug_url_to_service_translations.rb
    db/migrate/20110411125543_add_value_type_to_refinery_settings.rb
    db/migrate/20110411125540_create_refinerycms_core_schema.rb
    db/migrate/20110411125553_translate_custom_title_on_pages.rb
    db/migrate/20110411125551_translate_page_plugin.rb
    db/migrate/20110505151061_remove_cached_slug_from_services.rb
    db/migrate/20110411125554_remove_translated_fields_from_pages.rb
    db/migrate/20110411125548_remove_password_salt_from_users.rb
    db/migrate/20110411125549_create_refinerycms_images_schema.rb
    db/migrate/20110411125541_add_locale_to_slugs.rb
    db/migrate/20110517115625_create_download_categories.rb
    db/seeds
    db/seeds/services.rb
    db/seeds/downloads.rb
    db/seeds/download_categories.rb
    db/seeds/jobs.rb
    db/seeds/employees.rb
    db/seeds/references.rb
    db/seeds/offices.rb
    db/seeds/pages.rb
    db/seeds/dictionary_items.rb
    db/seeds.rb
    log
    log/development.log
    doc
    doc/README_FOR_APP
    tmp
    tmp/sockets
    tmp/sessions
    tmp/pids
    tmp/dragonfly
    tmp/dragonfly/cache
    tmp/dragonfly/cache/body
    tmp/dragonfly/cache/meta
    tmp/index
    tmp/index/development
    tmp/index/development/Page
    tmp/index/development/Page/107_97_114.ind
    tmp/index/development/Page/111.ind
    tmp/index/development/Page/111_100_112.ind
    tmp/index/development/Page/110_111_116.ind
    tmp/index/development/Page/102_111_117.ind
    tmp/index/development/Page/version
    tmp/index/development/Page/118_105_122.ind
    tmp/index/development/Page/112_97_103.ind
    tmp/index/development/Page/107_101.ind
    tmp/index/development/Page/112_111_106.ind
    tmp/index/development/Page/110_195.ind
    tmp/index/development/Page/112.ind
    tmp/index/development/Page/104_111_109.ind
    tmp/index/development/Page/104_105_115.ind
    tmp/index/development/Page/112_197.ind
    tmp/index/development/Page/115_108_111.ind
    tmp/index/development/Page/116_195.ind
    tmp/index/development/Page/109_105_115.ind
    tmp/index/development/Page/97.ind
    tmp/index/development/Page/115_108_117.ind
    tmp/index/development/Page/112_114_111.ind
    tmp/index/development/Page/115_116_97.ind
    tmp/index/development/Page/size
    tmp/index/development/Page/115_112_111.ind
    tmp/index/development/Page/114_101_102.ind
    tmp/index/development/Page/107_111_110.ind
    tmp/index/development/Page/104_111_100.ind
    tmp/index/development/Page/116_101_115.ind
    tmp/index/development/Service
    tmp/index/development/Service/49_54_48.ind
    tmp/index/development/Service/105_112_115.ind
    tmp/index/development/Service/version
    tmp/index/development/Service/115_101_111.ind
    tmp/index/development/Service/108_111_114.ind
    tmp/index/development/Service/109_111_98.ind
    tmp/index/development/Service/115_101_109.ind
    tmp/index/development/Service/112.ind
    tmp/index/development/Service/97_112_108.ind
    tmp/index/development/Service/112_111_112.ind
    tmp/index/development/Service/115_108_117.ind
    tmp/index/development/Service/112_111_100.ind
    tmp/index/development/Service/size
    tmp/index/development/Service/112_112_99.ind
    tmp/index/development/Service/118_195.ind
    tmp/index/development/RefinerySetting
    tmp/index/development/RefinerySetting/100_101_102.ind
    tmp/index/development/RefinerySetting/version
    tmp/index/development/RefinerySetting/112_97_103.ind
    tmp/index/development/RefinerySetting/97_112_112.ind
    tmp/index/development/RefinerySetting/115_105_116.ind
    tmp/index/development/RefinerySetting/117_115_101.ind
    tmp/index/development/RefinerySetting/115_116_114.ind
    tmp/index/development/RefinerySetting/102_114_111.ind
    tmp/index/development/RefinerySetting/99_97_99.ind
    tmp/index/development/RefinerySetting/109_101_110.ind
    tmp/index/development/RefinerySetting/115_117_112.ind
    tmp/index/development/RefinerySetting/100_114_97.ind
    tmp/index/development/RefinerySetting/size
    tmp/index/development/RefinerySetting/97_99_116.ind
    tmp/index/development/RefinerySetting/97_110_97.ind
    tmp/index/development/RefinerySetting/105_49_56.ind
    tmp/index/development/RefinerySetting/97_117_116.ind
    tmp/cache
    Gemfile
    script
    script/rails
  )
  
end
